#!/usr/bin/python3

import sys
from poison import sendSpoofedArp
from arguments import validate_arguments

def main():
    args = sys.argv[1:]
    validate_arguments(args)
    sendSpoofedArp()


if __name__ == "__main__":
    main()