#!/usr/bin/python3

import sys
from poison import sendSpoofedArp
from arguments import parse_arguments

def main():
    main_args = sys.argv[1:]
    args = parse_arguments(main_args)
    sendSpoofedArp(**args)


if __name__ == "__main__":
    main()